name: flutter_crud_sederhana
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.7
  flutter_svg: ^0.22.0
  device_info_plus: ^4.0.1
  flutter_device_identifier: ^0.0.1
  shared_preferences: ^2.0.13
  connectivity: ^3.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/poster.png
    - assets/images/logo.png
    - assets/images/round_icon1.svg
    - assets/images/round_icon2.svg
    - assets/images/sheft_row_left.svg
    - assets/images/sheft_row_right.svg
    - assets/images/perizinan.svg
    - assets/images/shift.svg
    - assets/images/lembur.svg
    - assets/images/ic_istirahat.svg
    - assets/images/ic_visit.svg
    - assets/images/ic_pulang.svg
    - assets/images/ic_activity.svg
    - assets/images/ic_news.svg
    - assets/images/ic_reimbursement.svg
    - assets/images/ic_salary.svg
    - assets/images/ic_location.svg
    - assets/images/ic_add.svg
    - assets/images/ic_send.svg
    - assets/images/munir.jpg
    - assets/images/no_connection.png
    - assets/images/image_login.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik_light.ttf
        - asset: fonts/rubik_medium.ttf

  #           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
